AllCops:
  TargetRubyVersion: 3.1

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 200

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/FileName:
  Enabled: false
